### PR TITLE
Adding a minimalistic IIIF Image API 1.1 support and corresponding test files

### PR DESCRIPTION
**Pull request by julienperret**
Tested with gallica iiif. I will try to deploy a working version for proof (if I can figure out how to deploy) ;)

### CODE REVIEW

**Comment by bertspaan** [comment]
Thanks Julien! I've merged your PR into https://github.com/allmaps/allmaps/tree/iiif-image-api1.1, I'll make a few tiny changes before merging your work into the develop branch.

**Comment by bertspaan** [comment]
@julienperret I've merged your PR into the develop branch. Before merging, I made a few changes to the code in your PR. You can see what I did here: https://github.com/allmaps/allmaps/commit/94aa9417a5d8517de2717471c934a920951ca8cb. Maybe you can have a look and see if I made a mistake somewhere.

I'll deploy versions of Allmaps Viewer and Allmaps Editor with IIIF Image API 1.0 support in the coming weeks.

**Comment by julienperret** [comment]
Thanks @bertspaan !
I tested the dev.viewer.allmaps.org with our annotation of the Verniquet Atlas from Gallica (https://raw.githubusercontent.com/soduco/webgl2-preview/main/static/annotation_verniquet_bnf.json) and it works very well!
(It is a bit slow to fetch the 72 info.json files though)

**Comment by bertspaan** [comment]
I've just replaced the old viewer.allmaps.org with the new dev.viewer.allmaps.org! Great to hear it's working well.

I can further optimize loading large map collections to make the viewer much faster.

Currently, it's loading every info.json _and_ a thumbnail of each map before displaying anything. The thumbnails are used to determine the map's background color.

I can do a few things to optimize this:

1. Only load the info.json files when needed (when the map is in the current viewport)
2. Assume some defaults about each map's IIIF server, and only load the info.json when these defaults don't work. The info.json is needed to know the IIIF Image's `tiles` values and compliance level. I can start loading images and progressively load info.json files, replacing the defaults.
3. Move loading info.json files and thumbnails to a Web Worker.
4. Only use 1 thumbnail to determine the background color, or sample random pixels from WebGL to determine background color

**Comment by sammeltassen** [comment]
5. Embed the info.json in the annotation (or IIIF Canvas if the annotation is embedded). This is allowed according to the spec, no?
6. Create a kind of magic wand button for automatically determining the background color when needed

**Comment by julienperret** [comment]
This is all great! 
We tested with annotation files we pushed to dataverse: https://viewer.allmaps.org/?url=https%3A%2F%2Fdataverse.harvard.edu%2Fapi%2Faccess%2Fdatafile%2F7002615

Should be keep the request open to keep track of the optimisation possibilities or close it and put them somewhere else?
Thanks again!!!

**Comment by bertspaan** [comment]
I'll keep working on optimizing Allmaps Viewer (and the OpenLayers plugin) the coming months, it's probably a good idea to turn the optimization ideas from the comment above into Issues, I'll do that!

**Comment by sammeltassen** [comment]
Julien, the example you shared is amazing but not V1.1, right?? All images come from the David Rumsey collection and are V2:

- https://www.davidrumsey.com/luna/servlet/iiif/RUMSEY~8~1~305629~90076036/info.json

Here are two V1 examples from Gallica:

- https://viewer.allmaps.org/?url=https%3A%2F%2Fannotations.allmaps.org%2Fimages%2Ff93f25ac5aaeaecb
- https://viewer.allmaps.org/?url=https%3A%2F%2Fannotations.allmaps.org%2Fimages%2Fe6be480e05ce83a9

**Comment by julienperret** [comment]
@sammeltassen You're right, I used the wrong file. Here is the one with the BnF files: https://viewer.allmaps.org/?url=+https%253A%252F%252Fdataverse.harvard.edu%252Fapi%252Faccess%252Fdatafile%252F7002730

**Comment by sammeltassen** [comment]
Thanks!

The link that works for me (without the `+`): https://viewer.allmaps.org/?url=https%3A%2F%2Fdataverse.harvard.edu%2Fapi%2Faccess%2Fdatafile%2F7002730

Unfortunately Rumsey and Gallica are the slowest servers we came across... Rumsey's response time for just the info.json is ± 150ms here and Gallica's ± 1m!! (Rumsey perhaps doesn't have servers in Europe.)

And much of the loading speed can be approved with Bert's and my suggestions above.

**Pull request merged**
